name: Deploy Retrieve Document Function to Cloud Functions

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      # - name: "Deploy Search Companies Function to Cloud Functions"
      #   run: "gcloud functions deploy search_companies \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=cr_extraction \
      #     --entry-point=search_companies \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --set-env-vars=ENV=prod \
      #     --timeout=100s"
      # - name: "Deploy Download Files Function to Cloud Functions"
      #   run: "gcloud functions deploy download_files \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=cr_extraction \
      #     --entry-point=download_files \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --set-env-vars=ENV=prod \
      #     --timeout=240s"
      # - name: "Deploy LLM data standardization to cloud functions"
      #   run: "gcloud functions deploy standardize_data \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=llm_data_standardization \
      #     --entry-point=standardize_data \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --set-env-vars=ENV=prod \
      #     --set-env-vars OPENAI_API_KEY=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 \
      #     --timeout=100s"
      - name: "Get Table from PDF"
        run: "gcloud functions deploy extract_table \
          --gen2 \
          --runtime=python311 \
          --region=europe-west3 \
          --source=table_extraction \
          --entry-point=extract_table \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars=ENV=prod \
          --set-env-vars FORM_RECOGNIZER_ENDPOINT=https://scraper.cognitiveservices.azure.com/\
          --set-env-vars FORM_RECOGNIZER_KEY=8b2877ef2b52444886bb09e0c5be84e5 \
          --timeout=100s"
