name: Deploy Retrieve Document Function to Cloud Functions

on:
  push:
    branches: ["main", "feature/fixing-pipeline"]

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      # - name: "Deploy Search Companies Function to Cloud Functions"
      #   run: "gcloud functions deploy search_companies \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=cr_extraction \
      #     --entry-point=search_companies \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --set-env-vars=ENV=prod \
      #     --timeout=100s"
      # - name: "Deploy Download Files Function to Cloud Functions"
      #   run: "gcloud functions deploy download_files \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=cr_extraction \
      #     --entry-point=download_files \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --memory=1024Mi \
      #     --set-env-vars=ENV=prod,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
      #     --timeout=240s"
      # - name: "Deploy LLM data standardization to cloud functions"
      #   run: "gcloud functions deploy standardize_data \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=llm_data_standardization \
      #     --entry-point=standardize_data \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --memory=1024Mi \
      #     --set-env-vars=ENV=prod \
      #     --set-env-vars OPENAI_API_KEY=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,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
      #     --timeout=150s"
      # - name: "Get Table from PDF"
      #   run: "gcloud functions deploy extract_table \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=table_extraction \
      #     --entry-point=extract_table \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --memory=1024Mi \
      #     --set-env-vars=ENV=prod,FORM_RECOGNIZER_ENDPOINT=https://scraper.cognitiveservices.azure.com/,FORM_RECOGNIZER_KEY=8b2877ef2b52444886bb09e0c5be84e5,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
      #     --timeout=100s"
      # - name: "Get Structured Information from XML"
      #   run: "gcloud functions deploy get_structured_content \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=structured_info \
      #     --entry-point=get_structured_content \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --memory=1024Mi \
      #     --set-env-vars=ENV=prod,FORM_RECOGNIZER_ENDPOINT=https://scraper.cognitiveservices.azure.com/,FORM_RECOGNIZER_KEY=8b2877ef2b52444886bb09e0c5be84e5,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
      #     --timeout=100s"
      # - name: "Deploy Get SI File for Shareholders"
      #   run: "gcloud functions deploy get_shareholder_structured_info \
      #     --gen2 \
      #     --runtime=python311 \
      #     --region=europe-west3 \
      #     --source=cr_extraction \
      #     --entry-point=get_shareholder_structured_info \
      #     --trigger-http \
      #     --allow-unauthenticated \
      #     --set-env-vars=ENV=prod,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
      #     --timeout=240s"
      - name: "Deploy Add structured info to shareholders table"
        run: "gcloud functions deploy get_shareholder_details \
          --gen2 \
          --runtime=python311 \
          --region=europe-west3 \
          --source=structured_info_for_shareholders \
          --entry-point=get_shareholder_details \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars=ENV=prod,SUPABASE_URL=https://vzaliuejopysgkdewpip.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxpdWVqb3B5c2drZGV3cGlwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNTQ4MjYwMiwiZXhwIjoyMDIxMDU4NjAyfQ.IJRQA4brOCmZOmIe6E_RU5cpLGJ1zEthiesYGK9im6E \
          --timeout=240s"
