name: Test CR Extraction

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cr_extraction/requirements.txt
    
      - name: Install pytest
        run: |
            python -m pip install pytest

      - name: Run pytest for a specific test
        run: pytest -k test_cr_download_files
